apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-workshop-builder
spec:
  portal:
    registration:
      enabled: false
    capacity: 1
  workshops:
  - name: lab-workshop-builder
