apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-workshop-builder
spec:
  vendor: eduk8s.io
  title: Workshop Builder
  description: Workshop environment to assist in creating and testing workshop content.
  url: https://github.com/eduk8s/lab-workshop-builder
  content:
    image: quay.io/eduk8s/lab-workshop-builder:master
  session:
    namespaces:
      budget: medium
    resources:
      storage: 5Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
        plugins:
          enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
      webdav:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        namespace: $(workshop_namespace)
        name: $(session_namespace)-builder
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
