apiVersion: training.eduk8s.io/v1alpha1
kind: Workshop
metadata:
  name: lab-workshop-builder
spec:
  vendor: eduk8s.io
  title: Workshop Builder
  description: Workshop environment to assist in creating and testing workshop content.
  url: https://github.com/eduk8s/lab-workshop-builder
  image: quay.io/eduk8s/lab-workshop-builder:master
  session:
    budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
      webdav:
        enabled: true
    patches:
      containers:
      - name: workshop
        volumeMounts:
        - name: data
          mountPath: /home/eduk8s
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: $(session_namespace)-builder
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        namespace: $(workshop_namespace)
        name: $(session_namespace)-builder
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        namespace: $(workshop_namespace)
        name: $(session_namespace)-builder
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
